### ISSUE TITLE
How compile erlang without modules 'jinterface, odbc, wx'

### ISSUE THREAD

**Issue by denegny** [HashNuke/asdf-erlang#83]
In compilation process require install erlang modules? how fix them?

``` erlang

 * jinterface     : No Java compiler found
 * odbc           : ODBC library - link check failed
 * wx             : wxWidgets not found, wx will NOT be usable
```

**Comment by Stratus3D** [comment]
First you'll need to have Java, ODBC, and WxWidgets installed on your computer. You may also have to pass various flags to the build. Refer to the installation notes for the version of Erlang you are trying to install for more information. You may also find some information on this in the kerl readme: https://github.com/kerl/kerl

**Comment by chakming** [comment]
i tried to follow this to install everything
```
sudo apt-get install automake autoconf libreadline-dev libncurses-dev \
libssl-dev libyaml-dev libxslt-dev libffi-dev libtool unixodbc-dev \
libwxgtk3.0-dev libgl1-mesa-dev  libglu1-mesa-dev libssh-dev xsltproc fop \
libxml2-utils
```

**Comment by denegny** [comment]
@chakming 

```
 * odbc           : ODBC library - link check failed
 * wx             : wxWidgets not found, wx will NOT be usable
is ok```

`* jinterface     : No Java compiler found`
still    report ((

> openjdk-11-jdk
is installed

**Comment by chakming** [comment]
did you try `sudo apt-get install default-jdk`?

**Comment by juliocabrera820** [comment]
> i tried to follow this to install everything and it works
> 
> ```
> sudo apt-get install automake autoconf libreadline-dev libncurses-dev \
> libssl-dev libyaml-dev libxslt-dev libffi-dev libtool unixodbc-dev \
> libwxgtk3.0-dev libgl1-mesa-dev  libglu1-mesa-dev libssh-dev xsltproc fop \
> libxml2-utils
> ```



libwxgtk3.0-dev was changed to libgtk3.0-gtk3-dev in 20.04.

**Comment by otakenz** [comment]
> 
> 
> > i tried to follow this to install everything and it works
> > ```
> > sudo apt-get install automake autoconf libreadline-dev libncurses-dev \
> > libssl-dev libyaml-dev libxslt-dev libffi-dev libtool unixodbc-dev \
> > libwxgtk3.0-dev libgl1-mesa-dev  libglu1-mesa-dev libssh-dev xsltproc fop \
> > libxml2-utils
> > ```
> 
> libwxgtk3.0-dev was changed to libgtk3.0-gtk3-dev in 20.04.

typo, libwxgtk3.0-gtk3-dev is the correct one

**Comment by hirusi** [comment]
> 
> 
> > > i tried to follow this to install everything and it works
> > > ```
> > > sudo apt-get install automake autoconf libreadline-dev libncurses-dev \
> > > libssl-dev libyaml-dev libxslt-dev libffi-dev libtool unixodbc-dev \
> > > libwxgtk3.0-dev libgl1-mesa-dev  libglu1-mesa-dev libssh-dev xsltproc fop \
> > > libxml2-utils
> > > ```
> > 
> > 
> > libwxgtk3.0-dev was changed to libgtk3.0-gtk3-dev in 20.04.
> 
> typo, libwxgtk3.0-gtk3-dev is the correct one

This wants to install the entirety of Ubuntu on WSL2.

If any other Windows peasants such as myself want to share what this needs, please. 🥇

**Comment by freemankevin** [comment]
如果是centos 7，应该安装哪部分的依赖呢？？

**Comment by GodzillaHua** [comment]
> 如果是centos 7，应该安装哪部分的依赖呢？？

yum install gcc-c++ automake cmake ncurses-devel openssl-devel wxGTK3-devel fop java-1.8.0-openjdk-devel unixODBC-devel libssh2-devel
